### ISSUE TITLE
Simple tutorial

### ISSUE THREAD

**Issue by amarszalek** [yuvipanda/nfs-flex-volume#1]
Hi,
Could you explain command by command how use it together with 'zero-to-jupyterhub-k8s'. I configured my own kubernetes cluster on local machines (one master, three nodes) and jupyterhub according to 'zero-to-jupyterhub-k8s' but for now i don't use any storage method. Do you know any better/simpler way to preserve data/notebooks on local machines.

**Comment by yuvipanda** [comment]
Heya!

It depends on what you are most familiar with :) NFS is perhaps the simplest to get started with, but has problems of its own long term. But if you've a small cluster and are just getting started, I'd recommend setting up your own NFS server and then using an [nfs volume](https://kubernetes.io/docs/concepts/storage/volumes/#nfs) to mount that for JupyterHub. 

I've filed an issue to document storage options better: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/356

**Comment by yuvipanda** [comment]
I'm archiving this repo - for others finding this issue, I'd suggest just using the built-in NFS support in kubernetes.

I hope you were able to solve your problems, @amarszalek!
